import configUtilities

CONS_EPS_NEW = 0   ##### New Record
CONS_EPS_MESSAGE_PUSHED_TO_QUEUE = 1
LIST_PROC_MAX = 100000


CONS_E1_1_QUEUE = 'RMQ1'

CONS_HOME_LINK_TABLE    = "H"
CONS_FOREIGN_LINK_TABLE = "F"
CONS_CONTACT_LINK_TABLE = "C"


